apiVersion: v1
kind: Service
metadata:
  name: psql-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: psql
  ports:
    - port: 6000
      targetPort: 6000
___
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: psql
  template:
    metadata:
      labels:
        component: psql
    spec:
      containers:
        - name: psql
          image: biotux7/psql
          ports:
            - containerPort: 6000
